vich_uploader:
  db_driver: orm

  mappings:
    participant_images:
      uri_prefix: /image/participants
      upload_destination: '%kernel.project_dir%/public/image/participants'
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

      inject_on_load: false
      delete_on_update: true
      delete_on_remove: true